#!/usr/bin/env python3
"""Produce a drop-in single-header distribution of SoaTable.

The core ``soatable.hpp`` is self-contained, so by default this stamps a provenance banner onto a
copy of it. SoaTable's extra capabilities live in opt-in add-on headers (compute, query, serialize,
...); pass ``--with`` to inline chosen add-ons into the same single header for drop-in vendoring.
Their own ``#include "soatable/..."`` lines and ``#pragma once`` guards are stripped so the result is
one self-consistent header.

Usage:
    python scripts/amalgamate.py [--output dist/soatable.hpp] [--with compute,query]
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
INCLUDE_DIR = REPO_ROOT / "include" / "soatable"
CORE = INCLUDE_DIR / "soatable.hpp"

# Add-on headers that may be bundled with --with (in a safe include order).
ADDONS = [
    "compute",
    "query",
    "serialize",
    "timeseries",
    "units",
    "dynamic",
    "reflect",
    "pmr",
    "concurrent",
    "mmap",
]

_LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"soatable/.*"\s*$')
_PRAGMA_ONCE = re.compile(r"^\s*#\s*pragma\s+once\s*$")


def read_version() -> str:
    """Return the project version from VERSION.txt (falling back to CMakeLists.txt)."""
    version_file = REPO_ROOT / "VERSION.txt"
    if version_file.is_file():
        return version_file.read_text(encoding="utf-8").strip()
    text = (REPO_ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    match = re.search(r"project\(\s*\w+\s+VERSION\s+([0-9]+\.[0-9]+\.[0-9]+)", text)
    if match is None:
        sys.exit(
            "Could not determine project version (no VERSION.txt or literal in CMakeLists.txt)"
        )
    return match.group(1)


def build_banner(version: str, addons: list[str]) -> str:
    """Return the provenance comment prepended to the amalgamated header."""
    year = datetime.date.today().year
    bundled = ", ".join(["core", *addons]) if addons else "core"
    return (
        "// SoaTable - single-header amalgamation\n"
        f"// Version: {version}\n"
        f"// Bundled: {bundled}\n"
        f"// Generated: {datetime.date.today().isoformat()}\n"
        "// Source: https://github.com/bbalouki/soatable\n"
        f"// License: MIT (c) {year} Bertin Balouki SIMYELI. See LICENSE in the repository.\n"
        "//\n"
        "// This file is generated by scripts/amalgamate.py. Do not edit by hand.\n"
        "\n"
    )


def strip_header(text: str, drop_pragma: bool) -> str:
    """Drop local soatable includes (and optionally the include guard) from a header's text."""
    kept = []
    for line in text.splitlines():
        if _LOCAL_INCLUDE.match(line):
            continue
        if drop_pragma and _PRAGMA_ONCE.match(line):
            continue
        kept.append(line)
    return "\n".join(kept).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=REPO_ROOT / "dist" / "soatable.hpp",
        help="Destination path for the amalgamated header.",
    )
    parser.add_argument(
        "--with",
        dest="addons",
        default="",
        help="Comma-separated add-on headers to inline (e.g. compute,query). Use 'all' for every one.",
    )
    args = parser.parse_args()

    if not CORE.is_file():
        sys.exit(f"Core header not found: {CORE}")

    if args.addons.strip().lower() == "all":
        selected = list(ADDONS)
    elif args.addons.strip():
        selected = [name.strip() for name in args.addons.split(",") if name.strip()]
    else:
        selected = []

    unknown = [name for name in selected if name not in ADDONS]
    if unknown:
        sys.exit(f"Unknown add-on(s): {', '.join(unknown)}. Known: {', '.join(ADDONS)}")
    # Preserve the safe ADDONS order regardless of how they were listed.
    selected = [name for name in ADDONS if name in selected]

    version = read_version()
    parts = [build_banner(version, selected), "#pragma once\n\n"]
    parts.append(strip_header(CORE.read_text(encoding="utf-8"), drop_pragma=True))
    for name in selected:
        path = INCLUDE_DIR / f"{name}.hpp"
        if not path.is_file():
            sys.exit(f"Add-on header not found: {path}")
        parts.append(f"\n// ===== soatable/{name}.hpp =====\n")
        parts.append(strip_header(path.read_text(encoding="utf-8"), drop_pragma=True))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("".join(parts), encoding="utf-8")
    label = ", ".join(["core", *selected]) if selected else "core"
    print(f"Wrote {args.output} (SoaTable {version}; bundled: {label})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
