#!/usr/bin/env python3
"""Produce a drop-in single-header distribution of SoaTable.

SoaTable is already a single header, so amalgamation simply stamps a provenance banner (version and
license pointer) onto a copy. The script exists so the published artifact is reproducible and so the
process generalizes if the library is ever split across multiple headers.

Usage:
    python scripts/amalgamate.py [--output dist/soatable.hpp]
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = REPO_ROOT / "include" / "soatable" / "soatable.hpp"


def read_version() -> str:
    """Extract the project version from the top-level CMakeLists.txt."""
    text = (REPO_ROOT / "CMakeLists.txt").read_text(encoding="utf-8")
    match = re.search(r"project\(\s*\w+\s+VERSION\s+([0-9]+\.[0-9]+\.[0-9]+)", text)
    if match is None:
        sys.exit("Could not determine project version from CMakeLists.txt")
    return match.group(1)


def build_banner(version: str) -> str:
    """Return the provenance comment prepended to the amalgamated header."""
    year = datetime.date.today().year
    return (
        "// SoaTable - single-header amalgamation\n"
        f"// Version: {version}\n"
        f"// Generated: {datetime.date.today().isoformat()}\n"
        "// Source: https://github.com/bbalouki/soatable\n"
        f"// License: MIT (c) {year}. See LICENSE in the repository.\n"
        "//\n"
        "// This file is generated by scripts/amalgamate.py. Do not edit by hand.\n"
        "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=REPO_ROOT / "dist" / "soatable.hpp",
        help="Destination path for the amalgamated header.",
    )
    args = parser.parse_args()

    if not HEADER.is_file():
        sys.exit(f"Header not found: {HEADER}")

    version = read_version()
    content = build_banner(version) + HEADER.read_text(encoding="utf-8")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} (SoaTable {version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
